config/routes.rb
Depot::Application.routes.draw do
  get "store/index"
  get "store/add_to_cart"
  get "home/index"

  resources :products

    match '/store/index' => "store#index", :as => :store_path
    match '/store/empty_cart' => "store#empty_cart", :as => :store_empty_cart
    match '/store/add_to_cart' => "store#add_to_cart", :as => :store_add_to_cart
    match '/' => "home#index", :as => :home

  root :to => 'home#index'

end

app/models/cart.rb
class Cart
    attr_reader :items

    def initialize
        @items = []
    end

    def add_product(product)
        current_item = @items.find {|item| item.product == product}
        if current_item
            current_item.increment_quantity
        else
            current_item = CartItem.new(product)
            @items << current_item
        end
        current_item
    end

    def total_price
        @items.sum {|item| item.price}
    end
end

app/models/cart_item.rb
class CartItem

    attr_reader :product, :quantity

    def initialize(product)
        @product = product
        @quantity = 1
    end
    
    def increment_quantity
        @quantity += 1
    end

    def title
        @product.title
    end

    def price
        @product.price * @quantity
    end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :description, :image_url, :price
  validates_presence_of :title, :description, :image_url
  validates_numericality_of :price
  validate :price_must_be_at_least_a_cent
  validates_uniqueness_of :title
  validates_format_of :image_url,
      :with => %r{\.(gif|jpg|png)$}i,
      :message => 'must be a url for GIF, JPG, or PNG image.'

  protected
  def price_must_be_at_least_a_cent
      errors.add(:price, 'should be at least 0.01') if price.nil? || price < 0.01
  end

  def self.find_products_for_sale
    find(:all, :order => "title")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def add_to_cart
      product = Product.find(params[:id])
      @cart = find_cart
      @current_item = @cart.add_product(product)
      respond_to do |format|
          format.js if request.xhr?
          format.html {redirect_to_index}
      end
  rescue ActiveRecord::RecordNotFound
      logger.error("Attempt to access invalid product #{params[:id]}")
      redirect_to_index("Invalid Product")
  end
  
  def empty_cart
    session[:cart] = nil
    redirect_to_index("Your cart is currently empty")
  end

  def index
    @products = Product.find_products_for_sale
    @cart = find_cart
  end

  private
  def find_cart
      session[:cart] ||= Cart.new
  end

  def redirect_to_index(msg = nil)
      flash[:notice] = msg
      redirect_to :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Go to Products", products_path %>
<%= link_to "Go to Store", store_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <title>Products: <%= controller.action_name %></title>
        <%= stylesheet_link_tag 'scaffold', 'depot' %>
    </head>
    <body>

        <p style="color: green"><%= flash[:notice]%></p>
        <%= yield %>
    </body>
</html>

app/views/layouts/store.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <title>Pragprog Books Online Store</title>
        <%= stylesheet_link_tag "depot", :media => "all" %>
        <%= javascript_include_tag :defaults %>
    </head>
    <body id="store">
        <div id="banner">
            <%= image_tag("logo.png") %>
            <%= @page_title || "Pragmatic Bookshelf" %>
        </div>
        <div id ="columns">
            <div id="cart">
                <%= render(:partial => "cart", :object => @cart) %>
            </div>
            <div id="side">
                <%= link_to "Home", home_path %>
                <%= link_to "Products", products_path %>
                <%= link_to "Store", store_index_path %>
            </div>
            <div id="main">
                <% if flash[:notice] %>
                    <div id="notice"><%= flash[:notice] %></div>
                <% end -%>

                <%= yield :layout %>
            </div>
        </div>
    </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
      <%= f.label :price %><br />
      <%= f.text_field :price %><br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product-list">
<h1>Listing products</h1>

<table>
    <% for product in @products %>
        <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
            <td>
                <%= image_tag product.image_url, :class => 'list-image' %>
            </td>
            <td class ="list-description">
                <dl>
                    <dt><%=h product.title %></dt>
                    <dd><%=h truncate(product.description.gsub(/<.*?>/,''),
                        :length => 80) %></dd>
                </dl>
            </td>

            <td class="list-actions">
                <%= link_to 'Show', product %><br/>
                <%= link_to 'Edit', edit_product_path(product) %><br />
                <%= link_to 'Destroy', product, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
            </td>
        </tr>
    <% end %>
</table>
</div>
<br />
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
<b>Price:</b>
<%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<h1>Your Pragmatic Catalog</h1>

<% for product in @products -%>
    <div class="entry">
        <%= image_tag(product.image_url) %>
        <h3><%=h product.title %></h3>
        <%= product.description %>
        <div class="price-line">
            <span class="price"><%= number_to_currency(product.price) %></span>
            <%= button_to "Add to Cart", {:action => 'add_to_cart', :id => product}, :remote => true, :method => 'post' %>
    </div>
<% end %>